### ISSUE TITLE
Feature Request: Add `kubewarden-policy-template` GH topic tag (and any others)

### ISSUE THREAD

**Issue by agilgur5** [kubewarden/go-wasi-policy-template#68]
### Is your feature request related to a problem?

This repo is missing the standard [`kubewarden-policy-template`](https://github.com/topics/kubewarden-policy-template) GH topic tag as mentioned [in the org README](https://github.com/kubewarden/.github/blob/ac161d6223a21060b0fa3148b7316ad8dd6e0d22/profile/README.md?plain=1#L39) and https://github.com/kubewarden/.github/pull/19#issuecomment-2467179736.

It has no topic tags currently, so some other ones that could be relevant:
- as used in other policy repos in this org: [`kubernetes`](https://github.com/topics/kubernetes), [`webassembly`](https://github.com/topics/webassembly), [`policy-as-code`](https://github.com/topics/policy-as-code), [`kubernetes-security`](https://github.com/topics/kubernetes-security)
- specific to this repo: [`go`](https://github.com/topics/go), [`wasi`](https://github.com/topics/go)

### Solution you'd like

At minimum, add the `kubewarden-policy-template` GH topic tag to this repo.

I can't PR that, so opening an issue for it

### Alternatives you've considered

Otherwise change the org README if these topic tags are no longer relevant

**Comment by flavio** [comment]
I've added the missing tags to the repo. The template is [already mentioned](https://github.com/kubewarden/community/blob/036c4164a5994c430bf4c5cfca12d5670d87ce03/README.md?plain=1#L190) on the community page
